# Path-based labels
frontend:
  - src/app/**/*

backend:
  - src/app/api/**/*
  - src/app/lib/db/**/*

documentation:
  - '**/*.md'
  - docs/**/*

dependencies:
  - package.json
  - package-lock.json

test-files:
  - src/**/*.test.ts
  - src/**/*.test.tsx
  - src/**/*.spec.ts
  - src/**/*.spec.tsx

components:
  - src/app/components/**/*

# Scope-based labels (matching commitlint scopes)
scope:components:
  - src/app/components/**/*

scope:pages:
  - src/app/page.tsx
  - src/app/**/page.tsx

scope:api:
  - src/app/api/**/*

scope:hooks:
  - src/app/hooks/**/*

scope:lib:
  - src/app/lib/**/*

scope:utils:
  - src/app/utils/**/*

scope:styles:
  - src/app/styles/**/*

scope:config:
  - '*.config.js'
  - '*.config.ts'
  - .github/**/*

scope:assets:
  - public/**/*
  - src/app/assets/**/*

scope:r3f:
  - src/app/components/**/r3f/**/*
  - src/app/components/**/*3d*/**/*

scope:motion:
  - src/app/components/animations/**/*

scope:types:
  - src/types/**/*
  - '**/*.d.ts'

scope:content:
  - src/app/content/**/*

scope:3d:
  - src/app/components/**/*3d*/**/*
  - public/models/**/*

# Commit-type labels (matching commitlint types)
feat:
  - has_conventional_commit: '^feat'

fix:
  - has_conventional_commit: '^fix'

docs:
  - has_conventional_commit: '^docs'

style:
  - has_conventional_commit: '^style'

refactor:
  - has_conventional_commit: '^refactor'

perf:
  - has_conventional_commit: '^perf'

test:
  - has_conventional_commit: '^test'

build:
  - has_conventional_commit: '^build'

ci:
  - has_conventional_commit: '^ci'

chore:
  - has_conventional_commit: '^chore'

revert:
  - has_conventional_commit: '^revert'

animation:
  - has_conventional_commit: '^animation'

content:
  - has_conventional_commit: '^content'

layout:
  - has_conventional_commit: '^layout'

a11y:
  - has_conventional_commit: '^a11y'

# Semantic version impact labels
version:patch:
  - has_conventional_commit: '^(fix|refactor|perf|style|chore|docs|build|ci|test)'

version:minor:
  - has_conventional_commit: '^feat'

version:major:
  - has_conventional_commit: '^(feat|fix|refactor|perf).*\!:'
  - body_matches: 'BREAKING CHANGE:'
