name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed to push release commits and tags
  issues: write # Needed to comment on released issues/PRs
  pull-requests: write # Needed to comment on released PRs

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID_GALLERY: ${{ secrets.NOTION_DB_ID_GALLERY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Avoid potential conflicts with GH_TOKEN

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or your project's bun version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Format code
        run: bun run util:format

      - name: Lint code
        run: bun run util:lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      - name: Release
        run: bunx semantic-release

  merge-back:
    name: Merge main back to dev
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Using GITHUB_TOKEN which gets automatically available to the workflow
          # This token has the right permissions because of the 'permissions' section above
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge main into dev
        run: |
          git checkout dev
          git pull
          git merge --no-ff origin/main -m "chore(config): merge main back into dev [skip ci]"
          git push origin dev
