name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed to push release commits and tags
  issues: write # Needed to comment on released issues/PRs
  pull-requests: write # Needed to comment on released PRs
  # id-token: write # Uncomment if using OIDC for npm provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID_GALLERY: ${{ secrets.NOTION_DB_ID_GALLERY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Uncomment if publishing to npm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Avoid potential conflicts with GH_TOKEN

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your project's node version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      - name: Lint code
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Release
        run: npx semantic-release

  merge-back:
    name: Merge main back to dev
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Using GITHUB_TOKEN which gets automatically available to the workflow
          # This token has the right permissions because of the 'permissions' section above
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge main into dev
        run: |
          git checkout dev
          git pull
          git merge --no-ff origin/main -m "chore(config): merge main back into dev [skip ci]"
          git push origin dev
